source 'https://rubygems.org'

gem 'byebug'
gem 'pry'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rspec'
gem 'rspec'
gem 'rspec-core'
gem 'rspec-expectations'
gem 'rspec-mocks'
gem 'rspec-support'
